"Run to restore a backup file"

import os, sys, sqlite3, bz2

from cryptography.fernet import Fernet


# This is a key generated by:
# from cryptography.fernet import Fernet
# key = Fernet.generate_key()
#
# As this is shown on github, before going live generate a new key
# this should match the key used to encrypt the backup file

key = b'X_iVOrYmWlob2UjIHXIlnHWjaEQQPsTqiJB7sgaoaA4='


# the new database to be created
database_file = os.path.join(os.path.dirname(os.path.realpath(__file__)), 'main.db')


def readfile(filepath):
    "Returns the binary data from the file"
    with open(filepath, 'rb') as f:
        bdata = f.read()
    return bdata


def decrypt(bdata):
    "Decrypt the binary data, returns the unencrypted data"
    f = Fernet(key)
    return f.decrypt(bdata)

def uncompress(compressed_data):
    "Uncompresses the data and returns a string"
    return bz2.decompress(compressed_data).decode("utf-8")


def restoredatabase(sql_script):
    "Restore database"
    try:
        con = sqlite3.connect(database_file, detect_types=sqlite3.PARSE_DECLTYPES)
        con.execute("PRAGMA foreign_keys = 0")
        cur = con.cursor()
        cur.executescript(sql_script)
    except:
        return False
    finally:
        con.close()
    return True


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Error:usage should be restore.py <path to backup file>")
        sys.exit(1)
    if os.path.isfile(database_file):
        print(f"Error:The database file {database_file} already exists.")
        print("Delete or rename it before this program creates a new file.")
        sys.exit(1)
    filepath = os.path.abspath(os.path.expanduser(sys.argv[1]))
    if not os.path.isfile(filepath):
        print("Error:The backup file does not exist.")
        sys.exit(1)
    bdata = readfile(filepath)
    compressed_data = decrypt(bdata)
    sql_script = uncompress(compressed_data)
    if restoredatabase(sql_script):
        print("Database restored")
    else:
        print("Failed to restore the database")

